# GELink.mak

# This file was generated by GenMakMB, Copyright 2007 MapInfo Corp.
# Dependencies are generated by DepGenMB, also Copyright 2007 MapInfo Corp.


.SUFFIXES: .mb .mbo

!IFDEF CMPL
# don't need to anything
!ELSE
CMPL = ..\..\..\CORE\Win32\Debug\MI\mapbasic.exe -nosplash -d 
!ENDIF

!IFDEF LINK
# don't need to anything
!ELSE
LINK = ..\..\..\CORE\Win32\Debug\MI\mapbasic.exe -nosplash -l 
!ENDIF


SRC = GELink.mb GELink_ColPick.mb gelink_ExportKML.mb GELink_Main.mb GELink_Util.mb 
OBJ = GELink.mbo GELink_ColPick.mbo gelink_ExportKML.mbo GELink_Main.mbo GELink_Util.mbo 


.mb.mbo:
    $(CMPL) $<
    @if exist $*.err exit 1


all: GELink.mbx

CLEAN :
    @del *.mbo
    @del *.mbx
    @del *.err


GELink.mb : "GELink.def" "Win32API.def" 
GELink_ColPick.mb : "GELink.def" 
gelink_ExportKML.mb : "GELink.def" "Win32API.def" 
GELink_Main.mb : "GELink.def" 
GELink_Util.mb : "GELink.def" "Win32API.def" 


GELink.mbx : $(OBJ)
    @echo Linking.....
    $(LINK) GELink.mbp
    @if exist GELink.ERR echo Link failed.
