//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mdimap.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_MDIMAPTYPE                  129
#define IDD_OVERVIEW                    130
#define ID_MAP_OVERVIEW                 32772
#define ID_TOOLBAR_SELECTOR             32773
#define ID_MAP_UPDATEOVERVIEW           32773
#define ID_MAP_VIEWENTIRELAYER          32775
#define ID_TOOLBAR_GRABBER              32780
#define ID_TOOLBAR_ZOOMIN               32781
#define ID_TOOLBAR_ZOOMOUT              32782
#define ID_TOOLBAR_INFOTOOL             32783
#define ID_MAP_LAYERCONTROL             32785
#define ID_MAP_CREATETHEME              32794

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
