//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISamples.Properties {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Resources {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Resources() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISamples.Properties.Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Are you sure you want to delete this node?.
		/// </summary>
		internal static string CONFIRM_NODE_DELETE {
			get {
				return ResourceManager.GetString("CONFIRM_NODE_DELETE", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Delete Node.
		/// </summary>
		internal static string CONFIRM_NODE_DELETE_MSG_TITLE {
			get {
				return ResourceManager.GetString("CONFIRM_NODE_DELETE_MSG_TITLE", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Must enter the name of view..
		/// </summary>
		internal static string ERR_EMPTY_VIEW_NAME {
			get {
				return ResourceManager.GetString("ERR_EMPTY_VIEW_NAME", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to View Name.
		/// </summary>
		internal static string ERR_EMPTY_VNAME_MSG_TITLE {
			get {
				return ResourceManager.GetString("ERR_EMPTY_VNAME_MSG_TITLE", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Front window is not a mapper..
		/// </summary>
		internal static string ERR_FRONT_WIN_NOT_MAPPER {
			get {
				return ResourceManager.GetString("ERR_FRONT_WIN_NOT_MAPPER", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Dropping a parent node on a child node is not allowed..
		/// </summary>
		internal static string ERR_INVALID_DROP {
			get {
				return ResourceManager.GetString("ERR_INVALID_DROP", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Invalid Drop.
		/// </summary>
		internal static string ERR_INVALID_DROP_MSG_TITLE {
			get {
				return ResourceManager.GetString("ERR_INVALID_DROP_MSG_TITLE", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Invalid XML.
		/// </summary>
		internal static string ERR_INVALID_XML {
			get {
				return ResourceManager.GetString("ERR_INVALID_XML", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Unable to display the dialog..
		/// </summary>
		internal static string ERR_MB_DLG_NOT_DISPLAYED {
			get {
				return ResourceManager.GetString("ERR_MB_DLG_NOT_DISPLAYED", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to A Map window must be open before you can use Named Views..
		/// </summary>
		internal static string ERR_NO_WIN_OPEN {
			get {
				return ResourceManager.GetString("ERR_NO_WIN_OPEN", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to About {0}.
		/// </summary>
		internal static string STR_ABOUT {
			get {
				return ResourceManager.GetString("STR_ABOUT", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to This application lets you save a Map window&apos;s current zoom and center as a named view. You assign each view a name (e.g. &apos;Downtown&apos;, &apos;North-east&apos;, etc.) Later, you can return to that view by choosing the name from a dialog..
		/// </summary>
		internal static string STR_ABT_DESC1 {
			get {
				return ResourceManager.GetString("STR_ABT_DESC1", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to To use Named Views, make a Map window the active window, then choose Tools &gt; Named Views.  Or, click on the Named Views button on the Tools buttonpad..
		/// </summary>
		internal static string STR_ABT_DESC2 {
			get {
				return ResourceManager.GetString("STR_ABT_DESC2", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to New Folder.
		/// </summary>
		internal static string STR_DEF_FOLDER_NAME {
			get {
				return ResourceManager.GetString("STR_DEF_FOLDER_NAME", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Named Views.
		/// </summary>
		internal static string STR_MB_APP_DESC {
			get {
				return ResourceManager.GetString("STR_MB_APP_DESC", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to NamedViews.MBX.
		/// </summary>
		internal static string STR_MB_APP_FILENAME {
			get {
				return ResourceManager.GetString("STR_MB_APP_FILENAME", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Display the Named Views dialog..
		/// </summary>
		internal static string STR_MB_BTN_PAD_HLPMSG {
			get {
				return ResourceManager.GetString("STR_MB_BTN_PAD_HLPMSG", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Tools.
		/// </summary>
		internal static string STR_MB_BTN_PAD_TOOLS {
			get {
				return ResourceManager.GetString("STR_MB_BTN_PAD_TOOLS", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to &amp;About Named Views....
		/// </summary>
		internal static string STR_MB_MNU_ABOUT {
			get {
				return ResourceManager.GetString("STR_MB_MNU_ABOUT", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to E&amp;xit Named Views.
		/// </summary>
		internal static string STR_MB_MNU_EXIT {
			get {
				return ResourceManager.GetString("STR_MB_MNU_EXIT", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to &amp;Named Views....
		/// </summary>
		internal static string STR_MB_MNU_NAMEDVIEWS {
			get {
				return ResourceManager.GetString("STR_MB_MNU_NAMEDVIEWS", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to &amp;Named Views.
		/// </summary>
		internal static string STR_MB_MNU_SUBTITLE {
			get {
				return ResourceManager.GetString("STR_MB_MNU_SUBTITLE", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Center = ({0}, {1}) - Zoom = {2} {3}.
		/// </summary>
		internal static string STR_TOOLTIP_VIEW {
			get {
				return ResourceManager.GetString("STR_TOOLTIP_VIEW", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Version {0}.
		/// </summary>
		internal static string STR_VERSION {
			get {
				return ResourceManager.GetString("STR_VERSION", resourceCulture);
			}
		}
	}
}
