//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by ICO16.RC
//
#define IDB_BITMAP1                     134
#define IDB_BITMAP2                     135
#define IDC_CURSOR1                     136

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
