'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete this node?.
        '''</summary>
        Friend ReadOnly Property CONFIRM_NODE_DELETE() As String
            Get
                Return ResourceManager.GetString("CONFIRM_NODE_DELETE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete Node.
        '''</summary>
        Friend ReadOnly Property CONFIRM_NODE_DELETE_MSG_TITLE() As String
            Get
                Return ResourceManager.GetString("CONFIRM_NODE_DELETE_MSG_TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Must enter the name of view..
        '''</summary>
        Friend ReadOnly Property ERR_EMPTY_VIEW_NAME() As String
            Get
                Return ResourceManager.GetString("ERR_EMPTY_VIEW_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View Name.
        '''</summary>
        Friend ReadOnly Property ERR_EMPTY_VNAME_MSG_TITLE() As String
            Get
                Return ResourceManager.GetString("ERR_EMPTY_VNAME_MSG_TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Front window is not a mapper..
        '''</summary>
        Friend ReadOnly Property ERR_FRONT_WIN_NOT_MAPPER() As String
            Get
                Return ResourceManager.GetString("ERR_FRONT_WIN_NOT_MAPPER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dropping a parent node on a child node is not allowed..
        '''</summary>
        Friend ReadOnly Property ERR_INVALID_DROP() As String
            Get
                Return ResourceManager.GetString("ERR_INVALID_DROP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Drop.
        '''</summary>
        Friend ReadOnly Property ERR_INVALID_DROP_MSG_TITLE() As String
            Get
                Return ResourceManager.GetString("ERR_INVALID_DROP_MSG_TITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid XML.
        '''</summary>
        Friend ReadOnly Property ERR_INVALID_XML() As String
            Get
                Return ResourceManager.GetString("ERR_INVALID_XML", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to display the dialog..
        '''</summary>
        Friend ReadOnly Property ERR_MB_DLG_NOT_DISPLAYED() As String
            Get
                Return ResourceManager.GetString("ERR_MB_DLG_NOT_DISPLAYED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A Map window must be open before you can use Named Views..
        '''</summary>
        Friend ReadOnly Property ERR_NO_WIN_OPEN() As String
            Get
                Return ResourceManager.GetString("ERR_NO_WIN_OPEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About {0}.
        '''</summary>
        Friend ReadOnly Property STR_ABOUT() As String
            Get
                Return ResourceManager.GetString("STR_ABOUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This application lets you save a Map window&apos;s current zoom and center as a named view. You assign each view a name (e.g. &apos;Downtown&apos;, &apos;North-east&apos;, etc.) Later, you can return to that view by choosing the name from a dialog..
        '''</summary>
        Friend ReadOnly Property STR_ABT_DESC1() As String
            Get
                Return ResourceManager.GetString("STR_ABT_DESC1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To use Named Views, make a Map window the active window, then choose Tools &gt; Named Views.  Or, click on the Named Views button on the Tools buttonpad..
        '''</summary>
        Friend ReadOnly Property STR_ABT_DESC2() As String
            Get
                Return ResourceManager.GetString("STR_ABT_DESC2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Folder.
        '''</summary>
        Friend ReadOnly Property STR_DEF_FOLDER_NAME() As String
            Get
                Return ResourceManager.GetString("STR_DEF_FOLDER_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Named Views.
        '''</summary>
        Friend ReadOnly Property STR_MB_APP_DESC() As String
            Get
                Return ResourceManager.GetString("STR_MB_APP_DESC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NamedViews.MBX.
        '''</summary>
        Friend ReadOnly Property STR_MB_APP_FILENAME() As String
            Get
                Return ResourceManager.GetString("STR_MB_APP_FILENAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display the Named Views dialog..
        '''</summary>
        Friend ReadOnly Property STR_MB_BTN_PAD_HLPMSG() As String
            Get
                Return ResourceManager.GetString("STR_MB_BTN_PAD_HLPMSG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tools.
        '''</summary>
        Friend ReadOnly Property STR_MB_BTN_PAD_TOOLS() As String
            Get
                Return ResourceManager.GetString("STR_MB_BTN_PAD_TOOLS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;About Named Views....
        '''</summary>
        Friend ReadOnly Property STR_MB_MNU_ABOUT() As String
            Get
                Return ResourceManager.GetString("STR_MB_MNU_ABOUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E&amp;xit Named Views.
        '''</summary>
        Friend ReadOnly Property STR_MB_MNU_EXIT() As String
            Get
                Return ResourceManager.GetString("STR_MB_MNU_EXIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Named Views....
        '''</summary>
        Friend ReadOnly Property STR_MB_MNU_NAMEDVIEWS() As String
            Get
                Return ResourceManager.GetString("STR_MB_MNU_NAMEDVIEWS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Named Views.
        '''</summary>
        Friend ReadOnly Property STR_MB_MNU_SUBTITLE() As String
            Get
                Return ResourceManager.GetString("STR_MB_MNU_SUBTITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Center = ({0}, {1}) - Zoom = {2} {3}.
        '''</summary>
        Friend ReadOnly Property STR_TOOLTIP_VIEW() As String
            Get
                Return ResourceManager.GetString("STR_TOOLTIP_VIEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version {0}.
        '''</summary>
        Friend ReadOnly Property STR_VERSION() As String
            Get
                Return ResourceManager.GetString("STR_VERSION", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
